name = "Justitia"
uuid = "b7a34101-e3cb-4dc6-8bd8-f09bffd6b65d"
authors = ["Joey Huchette <joehuchette@gmail.com>"]
version = "0.1.0"

[deps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
